#include "../Utils/Midl.h"

namespace HotCorner.Uwp.Devices {
	[default_interface]
	[bindable]
	runtimeclass MonitorInfo : XAML.Data.INotifyPropertyChanged, Windows.Foundation.IStringable {
		[noexcept]
		MonitorInfo(String id, String name);

		static Windows.Foundation.IAsyncOperation<MonitorInfo> FromDeviceAsync(Windows.Devices.Enumeration.DeviceInformation info);

		[noexcept]
		String Id{ get; };

		String DisplayName{ get; set; };

		[default_overload]
		Windows.Foundation.IAsyncAction RefreshAsync(Windows.Devices.Enumeration.DeviceInformationUpdate update);
		Windows.Foundation.IAsyncAction RefreshAsync(Windows.Devices.Enumeration.DeviceInformation info);
	}
}
