files:
  - source: /src/HotCorner.Package/Strings/en-US/Resources.resw
    translation: /src/HotCorner.Package/Strings/%locale%/Resources.resw
  - source: /src/HotCorner.Uwp/Strings/en-US/Resources.resw
    translation: /src/HotCorner.Uwp/Strings/%locale%/Resources.rew
