#include "../Utils/Midl.h"

namespace HotCorner.Uwp.Controls {
	[default_interface]
	[webhosthidden]
	runtimeclass EvenStackPanel : XAML.Controls.Panel {
		EvenStackPanel();

		DEPENDENCY_PROPERTY(Orientation, XAML.Controls.Orientation);
		DEPENDENCY_PROPERTY(Spacing, Double);
	}

	[default_interface]
	[webhosthidden]
	runtimeclass WrapPanel : XAML.Controls.Panel {
		WrapPanel();

		DEPENDENCY_PROPERTY(Orientation, XAML.Controls.Orientation);
		DEPENDENCY_PROPERTY(HorizontalSpacing, Double);
		DEPENDENCY_PROPERTY(VerticalSpacing, Double);
	}
}
