namespace HotCorner.Server {
	runtimeclass LifetimeManager {
		[default][interface_name("HotCorner.Server.ILifetimeManager", 898F12B7-4BB0-4279-B3B1-126440D7CB7A)]
		{
			void ReloadSettings();

			void TrackHotCorners();
			void StopTracking();

			void ShowTrayIcon();
			void HideTrayIcon();
		}
	}
}
