namespace HotCorner.Server {
	[default_interface]
	runtimeclass LifetimeManager {
		void ReloadSettings();

		void TrackHotCorners();
		void StopTracking();

		void ShowTrayIcon();
		void HideTrayIcon();
	}
}
