#include "../Utils/Midl.h"
import "Devices/Devices.idl";

namespace HotCorner.Uwp.Views {
	[default_interface]
	[webhosthidden]
	runtimeclass MainPage : XAML.Controls.UserControl {
		MainPage();
	}

	[default_interface]
	[webhosthidden]
	runtimeclass MonitorSettingsPage : XAML.Controls.UserControl {
		MonitorSettingsPage();

		void SetMonitorId(String id);
	}
}
