#include "../Utils/Midl.h"
import "Devices/Devices.idl";

namespace HotCorner.Uwp.Views {
	[default_interface]
	[webhosthidden]
	runtimeclass MainPage : XAML.Controls.UserControl {
		MainPage();
	}

	delegate void SettingAddedEventHandler(String monitorId, String monitorName);
	delegate void SettingRemovedEventHandler(String monitorId);

	[default_interface]
	[webhosthidden]
	runtimeclass MonitorSettingsPage : XAML.Controls.UserControl {
		MonitorSettingsPage();

		void SetMonitorId(String id);
		event SettingRemovedEventHandler SettingRemoved;
	}

	[default_interface]
	[webhosthidden]
	runtimeclass MonitorPickerFlyout : XAML.Controls.Flyout {
		MonitorPickerFlyout();

		void RestartWatcher();
		event SettingAddedEventHandler SettingAdded;
	}
}
