#pragma once

#define IDI_TRAYICON_ON_DARK 101
#define IDI_TRAYICON_ON_LIGHT 102
#define IDI_TRAYICON_OFF_DARK 103
#define IDI_TRAYICON_OFF_LIGHT 104
#define IDI_TRAYICON_HC_DARK 105
#define IDI_TRAYICON_HC_LIGHT 106

#define IDS_TRAY_TOOLTIP 60001
